language: python
python:
  - 3.6
install:
  - pip install -r requirements/base.txt
  - pip install -r requirements/test.txt
  - pip install codecov
script:
  - flake8
  - nosetests --with-coverage
  - codecov
